/**
 * Swedish, keyed by the English it replaces (design §7 item 11).
 *
 * Where the SM rules have a word, that word is used: the score keeper is the
 * *sekretariat*, the head referee the *ringdomare*, an exchange an *utväxling*, the final
 * exchange *sista utväxlingen*, and the warning ladder runs varning → poängavdrag →
 * förlust av match → diskvalificering. Sudden death is sudden death in the rules too.
 * Internal identifiers -- "red", "exchange", "quarter" -- are never translated on the
 * wire; only what a person reads.
 *
 * A key missing here comes out in English, and the i18n test fails the build for it.
 */
export const sv: Record<string, string> = {
  // --- colours and sides --------------------------------------------------------
  red: 'röd',
  blue: 'blå',
  green: 'grön',
  yellow: 'gul',
  orange: 'orange',
  purple: 'lila',
  white: 'vit',
  Red: 'Röd',
  Blue: 'Blå',
  'the {side} side': '{side} sida',
  '{side} competitor, shown in {colour}': '{side} fäktare, visad i {colour}',

  // --- event types, timer actions, end reasons (the editor) ---------------------
  exchange: 'utväxling',
  timer: 'klocka',
  undo: 'ångra',
  end: 'slut',
  options: 'alternativ',
  start: 'start',
  stop: 'stopp',
  resume: 'återuppta',
  reset: 'nollställ',
  time: 'tid',
  'point cap': 'poänggräns',
  penalty: 'bestraffning',
  forfeit: 'uppgiven',
  'final exchange': 'sista utväxlingen',
  'penalty cap': 'bestraffningsgräns',

  // --- organizer page: header, join panel ----------------------------------------
  Displays: 'Skärmar',
  Roster: 'Matchlista',
  'Pool sheets': 'Poolprotokoll',
  'Export JSON': 'Exportera JSON',
  'Export PDF': 'Exportera PDF',
  'Loading…': 'Laddar…',
  'Join from a tablet or phone': 'Anslut från surfplatta eller telefon',
  'on {network}': 'via {network}',
  Network: 'Nätverk',
  'This PC is on more than one network. Pick the one the tablets are on; the address and the code above follow the choice, and it is remembered.':
    'Den här datorn sitter på flera nätverk. Välj det som surfplattorna använder; adressen och koden ovan följer valet, och det kommer ihåg.',
  "Point a score keeper's device at that address, or let them scan the code. It opens straight on the mat picker.":
    'Skriv in adressen på sekretariatets enhet, eller låt dem skanna koden. Den öppnar direkt på mattvalet.',
  'No network': 'Inget nätverk',
  'This PC is not on a network another device could reach, so there is no address to hand out. Join it to the venue wifi and reload this page. Scoring on this PC still works.':
    'Den här datorn sitter inte på något nätverk som en annan enhet kan nå, så det finns ingen adress att dela ut. Anslut den till hallens wifi och ladda om sidan. Att föra protokoll på den här datorn fungerar ändå.',
  'Spare screens open': 'Extra skärmar öppnar',
  'and are told what to show from here, under Screens — or go straight to':
    'och får veta vad de ska visa härifrån, under Skärmar — eller går direkt till',
  or: 'eller',
  'Any device on the venue wifi can reach them.': 'Alla enheter på hallens wifi når dem.',
  'Score keeper': 'Sekretariat',
  'Mat {n}': 'Matta {n}',
  'mat {n}': 'matta {n}',
  Mat: 'Matta',
  Mats: 'Mattor',
  'QR code for {url}': 'QR-kod för {url}',

  // --- competitors ---------------------------------------------------------------
  Competitors: 'Fäktare',
  Competitor: 'Fäktare',
  '{n} entered': '{n} anmälda',
  Name: 'Namn',
  'Competitor name': 'Fäktarens namn',
  Club: 'Klubb',
  Add: 'Lägg till',
  Withdrawn: 'Utgått',
  Reinstate: 'Återinsätt',
  Withdraw: 'Stryk',
  Remove: 'Ta bort',
  "Pools are drawn, so competitors can only be withdrawn from here. A withdrawal voids their results as though they never entered, and everyone else's standings recompute.":
    'Poolerna är lottade, så fäktare kan bara strykas härifrån. En strykning tar bort deras resultat som om de aldrig deltagit, och alla andras tabellplaceringar räknas om.',

  // --- setup -----------------------------------------------------------------------
  Tournament: 'Turnering',
  'Smallest pool': 'Minsta pool',
  'Largest pool': 'Största pool',
  'Draw the pools': 'Lotta poolerna',
  'Draw the pools again': 'Lotta om poolerna',
  'Matches have already been scored. Drawing again replaces the pools and the results stop lining up with them.':
    'Matcher har redan protokollförts. Lottar du om ersätts poolerna och resultaten stämmer inte längre med dem.',
  Ruleset: 'Regelverk',
  'MSL, hardcoded · 8 points · 3 minutes · differential scoring': 'MSL, fast · 8 poäng · 3 minuter · differenspoäng',
  Ceiling: 'Tak',
  '4 mats, 8 pools of up to 7 — 56 competitors': '4 mattor, 8 pooler om upp till 7 — 56 fäktare',
  Data: 'Data',

  // --- pools -----------------------------------------------------------------------
  'Pool {n}': 'Pool {n}',
  'pool {n}': 'pool {n}',
  complete: 'klar',
  'in progress': 'pågår',
  moved: 'flyttad',
  'Moved by the organizer from where the draw put it': 'Flyttad av arrangören från där lottningen lade den',
  'Run this pool earlier on its mat': 'Kör poolen tidigare på sin matta',
  'Run this pool later on its mat': 'Kör poolen senare på sin matta',
  'Move pool {n} up': 'Flytta pool {n} uppåt',
  'Move pool {n} down': 'Flytta pool {n} nedåt',
  "Edit this match's log": 'Redigera matchens logg',
  'Edit the log of match {n}': 'Redigera loggen för match {n}',
  'Edit the log of {match}': 'Redigera loggen för {match}',
  'Matches completed': 'Utkämpade matcher',
  'Match point index': 'Matchpoängindex',
  'Victory index': 'Segerindex',
  'Score index': 'Punktindex',
  'Reception index, lowest wins': 'Mottaget index, lägst vinner',
  'Draw the pools to get started.': 'Lotta poolerna för att komma igång.',

  // --- eliminations -----------------------------------------------------------------
  Eliminations: 'Elimineringar',
  'top {n}, single elimination, sudden death': 'topp {n}, utslagning, sudden death',
  'Drawn from finished pools.': 'Lottas från färdigspelade pooler.',
  '1 pool match still to score.': '1 poolmatch kvar att protokollföra.',
  '{n} pool matches still to score.': '{n} poolmatcher kvar att protokollföra.',
  'Seeding · overall ranking across the pools': 'Seedning · sammanlagd ranking över poolerna',
  'Draw the eliminations': 'Lotta elimineringarna',
  'Draw the eliminations again': 'Lotta om elimineringarna',
  'Bracket matches have been scored. Drawing again replaces the bracket and the results stop lining up with it.':
    'Elimineringsmatcher har redan protokollförts. Lottar du om ersätts slutspelsträdet och resultaten stämmer inte längre med det.',
  'Quarter-finals': 'Kvartsfinaler',
  'Semi-finals': 'Semifinaler',
  'Quarter-final {n}': 'Kvartsfinal {n}',
  'Semi-final {n}': 'Semifinal {n}',
  'Bronze match': 'Bronsmatch',
  Final: 'Final',

  // --- screens and score keepers ---------------------------------------------------
  'Screens and score keepers': 'Skärmar och sekretariat',
  Screens: 'Skärmar',
  'None yet. Open': 'Inga ännu. Öppna',
  'on a screen and it appears here, waiting to be told what to show.':
    'på en skärm så dyker den upp här och väntar på att få veta vad den ska visa.',
  Alive: 'Ansluten',
  'Not seen for a while': 'Inte sedd på ett tag',
  'last seen {when}': 'senast sedd {when}',
  '{n} s ago': 'för {n} s sedan',
  '{n} min ago': 'för {n} min sedan',
  'Nothing yet': 'Inget ännu',
  'Mat {n} scoreboard': 'Resultattavla matta {n}',
  'Mat {n} audience display': 'Publikskärm matta {n}',
  'Every mat': 'Alla mattor',
  'Mats {a} and {b}': 'Mattorna {a} och {b}',
  'Match roster': 'Matchlista',
  'Score keepers': 'Sekretariat',
  'None connected.': 'Inga anslutna.',
  'Set aside': 'Undanlagda',
  'Exchanges a device sent after its match had been handed to another. Not counted. Check the match log before discarding; a hand edit is the way to recover any of it.':
    'Utväxlingar som en enhet skickade efter att dess match lämnats över till en annan. Räknas inte. Kontrollera matchloggen innan du kastar dem; en redigering för hand är sättet att få tillbaka något av det.',
  '1 exchange': '1 utväxling',
  '{n} exchanges': '{n} utväxlingar',
  'from {device} on {match}': 'från {device} i {match}',
  Discard: 'Kasta',

  // --- disciplines -------------------------------------------------------------------
  Disciplines: 'Discipliner',
  'Each discipline is its own run of the application, on its own port with its own data folder. Score keepers and screens join one discipline by its address; the name shows on every page so nobody has to guess which one they are on.':
    'Varje disciplin är en egen körning av programmet, på egen port med egen datamapp. Sekretariat och skärmar ansluter till en disciplin via dess adress; namnet visas på varje sida så att ingen behöver gissa vilken de är på.',
  Unnamed: 'Namnlös',
  'this one · port {n}': 'den här · port {n}',
  Stop: 'Stoppa',
  'Started from': 'Startad från',
  'Sabre, Rapier and dagger, …': 'Sabel, Rapir och dolk, …',
  'Start another discipline': 'Starta en disciplin till',

  // --- match editor -------------------------------------------------------------------
  'Edit the match log': 'Redigera matchloggen',
  'Edit the log': 'Redigera loggen',
  v: 'mot',
  Close: 'Stäng',
  Type: 'Typ',
  'Clock (s)': 'Klocka (s)',
  'of #{n}': 'av nr {n}',
  pts: 'poäng',
  warn: 'varn.',
  '{name} forfeits': '{name} ger upp',
  'display swapped': 'skärm speglad',
  Earlier: 'Tidigare',
  Later: 'Senare',
  'Move up': 'Flytta upp',
  'Move down': 'Flytta ned',
  'Delete this event': 'Ta bort händelsen',
  Delete: 'Ta bort',
  'Add an exchange': 'Lägg till en utväxling',
  'Add the end': 'Lägg till slutet',
  'Replays to': 'Spelas upp till',
  ended: 'avslutad',
  'not ended': 'inte avslutad',
  pending: 'väntar på',
  warnings: 'varningar',
  draw: 'oavgjort',
  Draw: 'Oavgjort',
  "Saving rewrites this match's log. The version being replaced is kept as a backup beside it":
    'Att spara skriver om matchens logg. Versionen som ersätts sparas som säkerhetskopia bredvid den',
  '({n} so far)': '({n} hittills)',
  'A score keeper holding the match reloads it.': 'Ett sekretariat som har matchen uppe laddar om den.',
  'Save the edited log': 'Spara den redigerade loggen',
  Cancel: 'Avbryt',

  // --- pool sheets ---------------------------------------------------------------------
  'Print A4': 'Skriv ut A4',
  'Print letter': 'Skriv ut Letter',
  'One sheet per pool. Turn background graphics off in the print dialog.':
    'Ett blad per pool. Stäng av bakgrundsgrafik i utskriftsdialogen.',
  '8 points or 3 minutes · differential scoring': '8 poäng eller 3 minuter · differenspoäng',
  Score: 'Poäng',
  Warnings: 'Varningar',
  'Match points: win 9, draw 6, loss 3. A penalty loss or a forfeit is recorded 0–8 and earns none. Second warning deducts a point; third loses the match.':
    'Matchpoäng: seger 9, oavgjort 6, förlust 3. Förlust på bestraffning eller uppgiven match noteras 0–8 och ger inga. Andra varningen drar av en poäng; tredje förlorar matchen.',
  'Pools have not been drawn yet.': 'Poolerna är inte lottade ännu.',

  // --- mat picker -------------------------------------------------------------------------
  'Which mat?': 'Vilken matta?',
  'Cannot reach the server:': 'Når inte servern:',
  'The server is out of reach. This is the schedule from the last time it was seen; scoring still works.':
    'Servern går inte att nå. Det här är schemat från senast den sågs; att föra protokoll fungerar ändå.',
  'Nothing up yet': 'Inget uppe ännu',
  'Waiting for the organizer to set up the mats.': 'Väntar på att arrangören ställer in mattorna.',
  'Pick the mat this device is sitting at. It stays on that mat for the whole event, and follows whichever match is up next there.':
    'Välj mattan som den här enheten står vid. Den stannar på den mattan hela tävlingen och följer den match som står på tur där.',

  // --- score keeper ---------------------------------------------------------------------------
  UNDO: 'ÅNGRA',
  'Double warning': 'Dubbel varning',
  'loses a point': 'poängavdrag',
  'Triple warning': 'Trippel varning',
  'loses the match': 'förlust av match',
  Forfeits: 'Ger upp',
  'recorded 0–8': 'noteras 0–8',
  Match: 'Match',
  'Colours and sides…': 'Färger och sidor…',
  'This screen': 'Den här skärmen',
  'Hand over this mat': 'Lämna över mattan',
  'to another device': 'till en annan enhet',
  'Try the other layout': 'Prova den andra layouten',
  Language: 'Språk',
  'SUDDEN DEATH': 'SUDDEN DEATH',
  'first point wins': 'första poängen vinner',
  PAUSE: 'PAUS',
  PLAY: 'STARTA',
  'Reset the clock to zero': 'Nollställ klockan',
  'Offline · {n} to send': 'Offline · {n} att skicka',
  "showing the server's scoring": 'visar serverns poäng',
  'Offline · schedule from {time}': 'Offline · schema från {time}',
  'Another device has taken over this match.': 'En annan enhet har tagit över matchen.',
  '1 exchange from this device was set aside for the organizer.': '1 utväxling från den här enheten lades undan till arrangören.',
  '{n} exchanges from this device were set aside for the organizer.': '{n} utväxlingar från den här enheten lades undan till arrangören.',
  'Leave the mat': 'Lämna mattan',
  'The server scores this match differently ({fields}):': 'Servern räknar matchen annorlunda ({fields}):',
  'here {local}, server {server}': 'här {local}, servern {server}',
  "Use the server's": 'Använd serverns',
  'Keep this one': 'Behåll den här',
  'NEXT MATCH': 'NÄSTA MATCH',
  'CONFIRM EXCHANGE': 'BEKRÄFTA UTVÄXLING',
  'Waiting for the {round}.': 'Väntar på {round}.',
  'Its competitors come from matches still running on the other mats.': 'Dess fäktare kommer från matcher som fortfarande pågår på de andra mattorna.',
  'Every match on mat {n} is done.': 'Alla matcher på matta {n} är klara.',
  'Nothing more is scheduled here. Check with the organizer.': 'Inget mer är inplanerat här. Stäm av med arrangören.',
  'Waiting for a match on mat {n}.': 'Väntar på en match på matta {n}.',
  'This screen follows the mat. It fills in when a match is up.': 'Den här skärmen följer mattan. Den fylls i när en match står på tur.',
  'Mat {n} is being scored by {device}': 'Matta {n} förs av {device}',
  'Take it over on this device? Anything the other device has not yet sent will be set aside for the organizer rather than counted.':
    'Ta över den på den här enheten? Allt den andra enheten inte hunnit skicka läggs undan till arrangören i stället för att räknas.',
  'Take over on this device': 'Ta över på den här enheten',
  'Undo the last exchange?': 'Ångra senaste utväxlingen?',
  'It is recorded as a correction, so nothing is lost from the log.': 'Den noteras som en rättelse, så inget försvinner ur loggen.',
  'Yes, undo it': 'Ja, ångra den',
  '{name} forfeits?': '{name} ger upp?',
  'Recorded 0–8. {winner} takes the win and the match points; {loser} earns none.':
    'Noteras 0–8. {winner} får segern och matchpoängen; {loser} får inga.',
  'Yes, {name} forfeits': 'Ja, {name} ger upp',
  'Reset the clock to 00:00?': 'Nollställ klockan till 00:00?',
  'For a clock that was started by mistake. The scores stay as they are, and the reset is recorded in the log.':
    'För en klocka som startades av misstag. Poängen står kvar, och nollställningen noteras i loggen.',
  'Yes, reset it': 'Ja, nollställ',
  'End match': 'Avsluta matchen',
  'Continue one more exchange': 'Fortsätt en utväxling till',
  'Undo last exchange': 'Ångra senaste utväxlingen',
  'Was that the final exchange?': 'Var det sista utväxlingen?',
  'Draw {score}': 'Oavgjort {score}',
  '{name} wins {score}': '{name} vinner {score}',
  '{name} wins on sudden death': '{name} vinner på sudden death',
  '{name} wins': '{name} vinner',
  '{name} is disqualified': '{name} diskvalificeras',
  '{name} loses the match on a double warning': '{name} förlorar matchen på dubbel varning',
  '{name} loses the match on a third warning': '{name} förlorar matchen på tredje varningen',
  'Both lose the match on warnings': 'Båda förlorar matchen på varningar',
  'Recorded 0–0. Neither earns match points.': 'Noteras 0–0. Ingen får matchpoäng.',
  'WARNING!': 'VARNING!',
  'DOUBLE!!': 'DUBBEL!!',
  'TRIPLE!!!': 'TRIPPEL!!!',
  score: 'poäng',
  '{n} warnings': '{n} varningar',
  Warning: 'Varning',

  // --- colours and sides sheet --------------------------------------------------------------------
  'Colours and sides': 'Färger och sidor',
  Sides: 'Sidor',
  'Swapping sides risks a screen that disagrees with the corners of the mat. A different colour is usually the better fix.':
    'Att byta sida riskerar en skärm som inte stämmer med mattans hörn. En annan färg är oftast den bättre lösningen.',
  'Swap sides on this screen': 'Byt sida på den här skärmen',
  'Swap sides on the displays': 'Byt sida på skärmarna',
  Done: 'Klar',

  // --- displays --------------------------------------------------------------------------------------
  'No match up yet': 'Ingen match uppe ännu',
  'Next on mat {n}': 'Näst på tur på matta {n}',
  'No more matches on mat {n}': 'Inga fler matcher på matta {n}',
  'Reconnecting…': 'Återansluter…',
  'No mats are set up yet.': 'Inga mattor är inställda ännu.',
  'Last match on mat {n}': 'Sista matchen på matta {n}',
  'On deck': 'På tur',
  'Nothing after the next match.': 'Inget efter nästa match.',
  'Nothing more on this mat.': 'Inget mer på den här mattan.',
  'Waiting for the organizer': 'Väntar på arrangören',
  'This screen is registered. The organizer picks what it shows from the organizer page, under Screens.':
    'Skärmen är registrerad. Arrangören väljer vad den visar från arrangörssidan, under Skärmar.',
  'Cannot reach the server. This screen will register itself as soon as it can.':
    'Når inte servern. Skärmen registrerar sig så snart den kan.',
  Tablet: 'Surfplatta',
  Phone: 'Telefon',
  Screen: 'Skärm',

  // --- 404 ------------------------------------------------------------------------------------------------
  'Nothing here': 'Inget här',
  'Try the': 'Prova',
  'organizer view': 'arrangörssidan',
  ', a mat display such as': ', en mattskärm som',
  ', or the roster at': ', eller matchlistan på',
};
